# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Computer Systems @ Colorado
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  The Computer Systems Research Lab @ the University of Colorado, Boulder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Department of Computer Science
address_line: 1111 Engineering Dr, Boulder, CO 80309
company_email: hello@LawOffice.org
google_map: https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d2347.067310795685!2d-105.26410547953404!3d40.0061593382523!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1553116892377

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections_dir: collections                                                             
collections:                                                                             
  students:
    output: true
  posts:
    output: true
  faculty:
    output: true
  postdocs:
    output: true
  headlines:
    output: true
